# Seeking can be "expensive", and causing the bot lagging, generally it can be controlled with limiting the seeking duration, set to false to disable seeking
allow_seek = true

# The duration limitation of seeking, denoted by seconds
seek_limit = 600

# Backward seeking is usually more "expensive", depends on the duration of the item being played, set it to true to enable backward seeking
allow_backward_seek = false

# The delay of command invoking, denoted by seconds, it means "there is only one command can be invoked in command_delay seconds", time for each guild is calculated separately
command_delay = 1

# Uncomment the below line to set the of owner of this bot, you need to set with a user id, which you can copy from a user's Discord page with your Developer mode enabled
#owner = 

# `true` to turn on and `false` to turn off auto saving, if it's on the data will be automatically saved at certain intervals, otherwise the data will only be saved when shutdown
auto_save = true

# The data will be automatically saved at a intervals specified by this value, denoted by seconds
auto_save_interval = 3600


[ytdlp]
# Use the yt-dlp that already in your environment
use_system = false

# Use nightly builds of yt-dlp
use_nightly = false

# Use bun that already in your environment for yt-dlp JS runtime
use_system_bun = false

# The path to your YouTube cookies in Netscape format, you can use extension like "Get cookies.txt LOCALLY" to get it
#cookies_path = ""