not_playing = "Not playing now."
user_not_in_voice_channel = "You are not in a voice channel."
bot_not_in_voice_channel = "turto is not in a voice channel."
different_voice_channel = "You are not in {bot_voice_channel}"
play = "â–¶ï¸ {title}"
pause = "â¸ï¸ {title}"
stop = "â¹ï¸ {title}"
join = "{voice_channel}â¬…ï¸ğŸ¢"
leave = "â¬…ï¸ğŸ¢{voice_channel}"
queue = "âœ… {title}"
remove = "â {title}"
url_not_found = "Can't find {url}"
invalid_url = "Please provide a valid url."
volume = "ğŸ”Š{volume}"
invalid_volume = "Enter a number ranges from 0 to 100."
toggle_autoleave = "Autoleave: {autoleave_status}"
invalid_autoleave = "Please specify whether to turn on or off autoleave."
invalid_seek = "Please enter a number between 0 and the seek limitation {seek_limit}."
seek_not_allow = "Seeking is not allow."
backward_seek_not_allow = "Backward seeking is not allowed."
administrator_only = "This command can only be invoked by an adminstrator."
user_got_banned = "{user} has been banned."
user_already_banned = "{user} had already been banned."
user_got_unbanned = "{user} has been unbanned."
user_not_banned = "{user} hasn't been banned yet."
banned_user_repsonse = "You are not allow to invoke any command because you are banned."
invalid_user = "Please specify a user by mentioning."